plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.app.calculadora'
    compileSdk 34

    defaultConfig {
        applicationId "com.app.calculadora"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    // Aqui nós dizemos para todas as ferramentas usarem o Java 17
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    kotlinOptions {
        jvmTarget = '17'
    }
}
